FROM node:18-alpine

WORKDIR /usr/app

COPY package*.json ./
COPY tsconfig.json ./
# Install ALL dependencies including devDependencies (for ts-node)
RUN npm ci

COPY src ./src
COPY tests ./tests

EXPOSE 3100

CMD ["npm", "run", "start:mock-server"]
