import { Model, ModelSpec } from '../core/model';

/**
 * BillingCharge - Individual charge generated by a BillingSchedule.
 *
 * Represents a single billing event created by a recurring schedule.
 * Tracks charge status, amount, and linked transaction.
 */
export class BillingCharge extends Model {
  static spec: ModelSpec = {
    object: 'billing_charge',
    endpoint: '/billing_charges',
  };

  get billingScheduleId(): string { return this.getStr('billing_schedule_id'); }
  get transactionId(): string { return this.getStr('transaction_id'); }
  get amount(): number { return this.getFloat('amount'); }
  get status(): string { return this.getStr('status'); }
  get chargeDate(): string { return this.getStr('charge_date'); }
  get attemptCount(): number { return this.getInt('attempt_count'); }
  get createdAt(): string { return this.getStr('created_at'); }
}
